// Generated by gencpp from file scara_cpe_kinematics/gotoxy.msg
// DO NOT EDIT!


#ifndef SCARA_CPE_KINEMATICS_MESSAGE_GOTOXY_H
#define SCARA_CPE_KINEMATICS_MESSAGE_GOTOXY_H

#include <ros/service_traits.h>


#include <scara_cpe_kinematics/gotoxyRequest.h>
#include <scara_cpe_kinematics/gotoxyResponse.h>


namespace scara_cpe_kinematics
{

struct gotoxy
{

typedef gotoxyRequest Request;
typedef gotoxyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct gotoxy
} // namespace scara_cpe_kinematics


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::scara_cpe_kinematics::gotoxy > {
  static const char* value()
  {
    return "d3402b21681d237b9cc577a12ce72624";
  }

  static const char* value(const ::scara_cpe_kinematics::gotoxy&) { return value(); }
};

template<>
struct DataType< ::scara_cpe_kinematics::gotoxy > {
  static const char* value()
  {
    return "scara_cpe_kinematics/gotoxy";
  }

  static const char* value(const ::scara_cpe_kinematics::gotoxy&) { return value(); }
};


// service_traits::MD5Sum< ::scara_cpe_kinematics::gotoxyRequest> should match 
// service_traits::MD5Sum< ::scara_cpe_kinematics::gotoxy > 
template<>
struct MD5Sum< ::scara_cpe_kinematics::gotoxyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::scara_cpe_kinematics::gotoxy >::value();
  }
  static const char* value(const ::scara_cpe_kinematics::gotoxyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::scara_cpe_kinematics::gotoxyRequest> should match 
// service_traits::DataType< ::scara_cpe_kinematics::gotoxy > 
template<>
struct DataType< ::scara_cpe_kinematics::gotoxyRequest>
{
  static const char* value()
  {
    return DataType< ::scara_cpe_kinematics::gotoxy >::value();
  }
  static const char* value(const ::scara_cpe_kinematics::gotoxyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::scara_cpe_kinematics::gotoxyResponse> should match 
// service_traits::MD5Sum< ::scara_cpe_kinematics::gotoxy > 
template<>
struct MD5Sum< ::scara_cpe_kinematics::gotoxyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::scara_cpe_kinematics::gotoxy >::value();
  }
  static const char* value(const ::scara_cpe_kinematics::gotoxyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::scara_cpe_kinematics::gotoxyResponse> should match 
// service_traits::DataType< ::scara_cpe_kinematics::gotoxy > 
template<>
struct DataType< ::scara_cpe_kinematics::gotoxyResponse>
{
  static const char* value()
  {
    return DataType< ::scara_cpe_kinematics::gotoxy >::value();
  }
  static const char* value(const ::scara_cpe_kinematics::gotoxyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SCARA_CPE_KINEMATICS_MESSAGE_GOTOXY_H
